# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

rails_version_path = File.expand_path(File.join(File.dirname(__FILE__), '..', '..', '.rails-version'))
rails_version = File.read(rails_version_path).strip.to_f
gem 'rails', "~> #{rails_version}"

gem 'mongoid'
gem 'pg'
