version: '3.9'

services:
  mongodb:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgresql:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    extra_hosts:
      - "host.docker.internal:host-gateway"

