commands:
  install-gems-command:
    steps:
      - checkout
      - run:
          name: Install Web gems with bundler
          command: bundle install
          environment:
            RAILS_ENV: test
  setup-postgresql-db-command:
    steps:
      - run:
          name: Setup PostgreSQL DB
          command: ./test/dummy/bin/setup 
          environment:
            RAILS_ENV: test
jobs:
  roar-responder-job:
    docker:
      - image: ruby:2.6-slim
      - image: mongo:5.0.3
      - environment:
          POSTGRES_PASSWORD: password
        image: postgres:13.2
    resource_class: small
    steps:
      - install-gems-command
      - setup-postgresql-db-command
      - run:
          name: Run tests
          command: bundle exec rake test
version: 2.1
workflows:
  roar-responder-workflow:
    jobs:
      - hold:
          type: approval
      - roar-responder-job:
          requires:
            - hold
