jobs:
  roar-responder-job:
    docker:
      - image: ruby:2.6
      - image: mongo:5.0.3
      - environment:
          POSTGRES_PASSWORD: password
        image: postgres:13.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install root gems
          command: bundle install
      - run:
          name: Setup Dummy
          command: ./test/dummy/bin/setup
      - run:
          name: Run tests
          command: bundle exec rake test
version: 2.1
workflows:
  roar-responder-workflow:
    jobs:
      - roar-responder-job
